# Generated by Django 4.0.3 on 2022-04-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='events_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('venue', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
    ]
