# Generated by Django 4.0.3 on 2022-04-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_events_db_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_db',
            name='date',
        ),
    ]
