# Generated by Django 4.0.3 on 2022-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_events_db_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_db',
            name='email',
        ),
        migrations.AddField(
            model_name='events_db',
            name='model_image',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
    ]
