# Generated by Django 4.0.3 on 2022-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_db_email_events_db_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_db',
            name='time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events_db',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
